---
title: "election"
author: "Shyamali Sheth"
format: html
execute: 
  echo: false
---


$$death_age = \beta{0} + \beta{1} treatmenti + \beta{2}win_margini + \beta{3}repubi + \beta{4}thirdpartyi + \epsilon{i}$$


```{r}
#| label: setup
#| message: false
library(tidyverse)
library(primer.data)
library(brms)
library(tidybayes)
library(gtsummary)
```

```{r}
#| cache: true

x <- governors |> 
  select(death_age, election_age, win_margin, party, sex) |> 
  mutate(treatment = ifelse(win_margin > 0, "win", "lose")) |> 
  filter(abs(win_margin) < 5) 

fit_elec_1 <- brm(formula = death_age ~ treatment + win_margin +
                 party,
                  data = x,
                  family = gaussian(),
                  refresh = 0,
                  silent = 2,
                  seed = 9)

fixef(fit_elec_1)

tbl_regression(fit_elec_1, 
               intercept = TRUE)
```



Temperance
Variables: Treatment, Party, Win margin

values: party: Democrat
        treatment: win, lose
        win_margin: 0


```{r}
ndata <- tibble(expand_grid(treatment = c("win", "lose"), 
                            party = c("Democrat", "Republican", "Third party"),
                            win_margin = 0))

fit_elec_1 |>
  add_epred_draws(newdata = ndata) |>
  ggplot(aes(x = .epred, y = party, fill = treatment))+
  stat_slab() +
  labs(title = "Expected Lifespan Given Election Outcome",
       subtitle = "Winning is associated with about 8 extra years",
       x = "Expected Lifespan",
       y = "",
       color = "Election Result")

```








